name             'apache'
maintainer       'The Authors'
maintainer_email 'ds.prashanth@yahoo.co.in'
license          'all_rights'
description      'Installs/Configures apache'
long_description 'Installs/Configures apache'
version          '0.3.0'
